[2023-03-20 11:33:33,173] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Hitesh\\Documents\\Assignment\\Assignment_2\\traveling\\artifact')
[2023-03-20 11:33:33,174] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Hitesh\\Documents\\Assignment\\Assignment_2\\traveling\\artifact')
[2023-03-20 11:33:33,174] root - INFO - Data Ingestion config: DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/Shivan118/Main-Branching/main/TourismData.csv', tgz_download_dir='C:\\Users\\Hitesh\\Documents\\Assignment\\Assignment_2\\traveling\\artifact\\data_ingestion\\2023-03-20-11-33-32\\tgz_data', raw_data_dir='C:\\Users\\Hitesh\\Documents\\Assignment\\Assignment_2\\traveling\\artifact\\data_ingestion\\2023-03-20-11-33-32\\raw_data', ingested_train_dir='C:\\Users\\Hitesh\\Documents\\Assignment\\Assignment_2\\traveling\\artifact\\data_ingestion\\2023-03-20-11-33-32\\ingested_data\\train', ingested_test_dir='C:\\Users\\Hitesh\\Documents\\Assignment\\Assignment_2\\traveling\\artifact\\data_ingestion\\2023-03-20-11-33-32\\ingested_data\\test')
[2023-03-20 11:33:33,177] root - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
[2023-03-20 11:33:33,177] root - INFO - Downloading file from :[https://raw.githubusercontent.com/Shivan118/Main-Branching/main/TourismData.csv] into :[C:\Users\Hitesh\Documents\Assignment\Assignment_2\traveling\artifact\data_ingestion\2023-03-20-11-33-32\tgz_data\TourismData.csv]
[2023-03-20 11:33:33,216] root - ERROR - 
        Error occured in script: 
        [ c:\Users\Hitesh\Documents\Assignment\Assignment_2\travelling\pipeline\pipeline.py ] at 
        try block line number: [36] and exception block line number: [39] 
        error message: [
        Error occured in script: 
        [ c:\Users\Hitesh\Documents\Assignment\Assignment_2\travelling\pipeline\pipeline.py ] at 
        try block line number: [27] and exception block line number: [29] 
        error message: [
        Error occured in script: 
        [ c:\Users\Hitesh\Documents\Assignment\Assignment_2\travelling\components\data_ingestion.py ] at 
        try block line number: [120] and exception block line number: [124] 
        error message: [
        Error occured in script: 
        [ c:\Users\Hitesh\Documents\Assignment\Assignment_2\travelling\components\data_ingestion.py ] at 
        try block line number: [40] and exception block line number: [45] 
        error message: [<urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>]
        ]
        ]
        ]
        
